name: note_pad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  timeago: ^3.7.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
